# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false
fortran: false

jobs:
  include:
  - r: devel
  - r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("hadley/emo")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: release
    env:
      - DEVEL_PACKAGES=true
    r_github_packages:
      - r-lib/vctrs
      - r-lib/rlang
      - tidyverse/magrittr
      - tidyverse/dplyr
      - tidyverse/purrr
      - hadley/assertthat
      - tidyverse/tidyselect
      - tidyverse/glue
      - tidyverse/tibble
      - r-lib/zeallot
env:
  global:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE

